Repository dwyl/phoenix-todo-list-tutorial, pull requests merged in 2022-12, with the labels that each got.

#59 PR: Deploy to Fly.io issue #52
  .dockerignore
  .github/dependabot.yml
  .github/workflows/ci.yml
  Dockerfile
  README.md
  assets/js/app.js
  coveralls.json
  fly.toml
  lib/app/mailer.ex
  lib/app/release.ex
  lib/app_web/components/layouts/app.html.heex
  lib/app_web/controllers/item_controller.ex
  lib/app_web/controllers/item_html.ex
  lib/app_web/controllers/item_html/edit.html.heex
  lib/app_web/controllers/item_html/index.html.heex
  lib/app_web/controllers/item_html/new.html.heex
  lib/app_web/router.ex
  mix.exs
  mix.lock
  rel/overlays/bin/migrate
  rel/overlays/bin/migrate.bat
  rel/overlays/bin/server
  rel/overlays/bin/server.bat
  test/app_web/controllers/item_controller_test.exs
  test/app_web/controllers/item_html_test.exs
Labels: enhancement, T25m, awaiting-review, technical

#58 [PR] `turbolinks` package clarification
  README.md
  assets/js/app.js
  assets/package-lock.json
  assets/package.json
  lib/app_web/components/layouts/root.html.heex
Labels: chore, awaiting-review

#56 [PR] Adding auth
  .env_sample
  README.md
  auth.md
  coveralls.json
  lib/app/todo.ex
  lib/app_web/controllers/auth_controller.ex
  lib/app_web/controllers/item_controller.ex
  lib/app_web/controllers/item_html/index.html.heex
  lib/app_web/router.ex
  mix.exs
  mix.lock
  test/app/todo_test.exs
  test/app_web/controllers/auth_controller_test.exs
  test/app_web/controllers/item_controller_test.exs
  test/app_web/controllers/item_html_test.exs
  test/support/fixtures/todo_fixtures.ex
  test/test_helper.exs
Labels: enhancement, in-review, technical

#60 [PR] Adding API
  README.md
  api.md
  config/dev.exs
  config/prod.exs
  config/test.exs
  lib/app/todo/item.ex
  lib/app_web/controllers/api_controller.ex
  lib/app_web/router.ex
  mix.exs
  mix.lock
  test/app/todo_test.exs
  test/app_web/controllers/api_controller_test.exs
Labels: enhancement, in-review, T25m
